// This file was auto-generated by prisma-generator-typescript-interfaces

export type ReservationStatus = "RESERVED" | "OCCUPIED" | "COMPLETED" | "CANCELLED";

export type VehicleType = "TWO_WHEEL" | "FOUR_WHEEL";

export type Role = "USER" | "ADMIN";

export interface ParkingReservation {
  id: string;
  slotId: string;
  vehicleId: string;
  userId: string;
  startTime: Date;
  endTime: Date | null;
  status: ReservationStatus;
  createdAt: Date;
  updatedAt: Date;
  slot?: ParkingSlot;
  vehicle?: Vehicle;
  user?: User;
}

export interface ParkingSlot {
  id: string;
  slotNumber: string;
  vehicleType: VehicleType;
  isAvailable: boolean;
  createdAt: Date;
  updatedAt: Date;
  reservations?: ParkingReservation[];
}

export interface User {
  id: string;
  email: string;
  username: string;
  password: string;
  role: Role;
  createdAt: Date;
  updatedAt: Date;
  reservations?: ParkingReservation[];
}

export interface Vehicle {
  id: string;
  plateNumber: string;
  type: VehicleType;
  createdAt: Date;
  reservations?: ParkingReservation[];
}
