// This file was auto-generated by prisma-generator-typescript-interfaces

export type Role = "USER" | "ADMIN";

export interface User {
  id: string;
  email: string;
  username: string;
  password: string;
  role: Role;
  createdAt: Date;
  updatedAt: Date;
}
